/* Replace with your SQL commands */
-- bizont_edms_general.user_data definition

CREATE TABLE bizont_edms_general.user_data (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_name varchar NULL,
	user_email varchar NULL,
	CONSTRAINT user_data_pk PRIMARY KEY (id)
);
CREATE INDEX user_data_user_email_idx ON bizont_edms_general.user_data USING btree (user_email);
CREATE INDEX user_data_user_name_idx ON bizont_edms_general.user_data USING btree (user_name);

-- Permissions

ALTER TABLE bizont_edms_general.user_data OWNER TO postgres;
GRANT ALL ON TABLE bizont_edms_general.user_data TO postgres;

INSERT INTO bizont_edms_general.user_data (id, user_name, user_email) VALUES(1, 'Mario', 'mario@bizont.ca');
INSERT INTO bizont_edms_general.user_data (id, user_name, user_email) VALUES(2, 'Lebron', 'lebron@bizont.ca');
