/* Replace with your SQL commands */
-- bizont_edms_general.events definition

-- Drop table

-- DROP TABLE bizont_edms_general.events;

CREATE TABLE bizont_edms_general.events (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	event_type int4 NULL,
	title varchar NULL,
	event_by varchar NULL,
	event_date timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	schema_name varchar NULL,
	table_name varchar NULL,
	entity_id int4 NOT NULL,
	entity_data jsonb NULL,
	CONSTRAINT audits_pk PRIMARY KEY (id)
);
CREATE INDEX audits_event_by_idx ON bizont_edms_general.events USING btree (event_by);
CREATE INDEX audits_event_date_idx ON bizont_edms_general.events USING btree (event_date);
CREATE INDEX audits_event_type_idx ON bizont_edms_general.events USING btree (event_type);
CREATE INDEX events_schema_idx ON bizont_edms_general.events USING btree (schema_name, table_name);

-- Permissions

ALTER TABLE bizont_edms_general.events OWNER TO postgres;
GRANT ALL ON TABLE bizont_edms_general.events TO postgres;