/* Replace with your SQL commands */
-- bizont_edms_general.roles_data definition

CREATE TABLE bizont_edms_general.roles_data (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	role_name varchar NULL,
	CONSTRAINT roles_data_pk PRIMARY KEY (id)
);
CREATE INDEX roles_data_role_name_idx ON bizont_edms_general.roles_data USING btree (role_name);

-- Permissions

ALTER TABLE bizont_edms_general.roles_data OWNER TO postgres;
GRANT ALL ON TABLE bizont_edms_general.roles_data TO postgres;

INSERT INTO bizont_edms_general.roles_data (id, role_name) VALUES(1, 'Admin');
INSERT INTO bizont_edms_general.roles_data (id, role_name) VALUES(2, 'Constellation Admin');
INSERT INTO bizont_edms_general.roles_data (id, role_name) VALUES(3, 'Contellation Editor');
INSERT INTO bizont_edms_general.roles_data (id, role_name) VALUES(4, 'Hipma Admin');
INSERT INTO bizont_edms_general.roles_data (id, role_name) VALUES(5, 'Hipma Editor');
