/* Replace with your SQL commands */

-- bizont_edms_general.permission_data definition

CREATE TABLE bizont_edms_general.permission_data (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	permission_name varchar NOT NULL,
	permission_desc varchar NULL,
	permission_category varchar NULL,
	CONSTRAINT permission_data_pk PRIMARY KEY (id),
	CONSTRAINT permission_data_un UNIQUE (permission_name)
);

-- Permissions

ALTER TABLE bizont_edms_general.permission_data OWNER TO postgres;
GRANT ALL ON TABLE bizont_edms_general.permission_data TO postgres;


INSERT INTO bizont_edms_general.permission_data (id, permission_name, permission_desc, permission_category) VALUES(13, 'dashboard_view', 'Dashboard View', 'General');
INSERT INTO bizont_edms_general.permission_data (id, permission_name, permission_desc, permission_category) VALUES(1, 'constellation_create', 'Constellation Create', 'Constellation');
INSERT INTO bizont_edms_general.permission_data (id, permission_name, permission_desc, permission_category) VALUES(2, 'constellation_delete', 'Constellation Delete', 'Constellation');
INSERT INTO bizont_edms_general.permission_data (id, permission_name, permission_desc, permission_category) VALUES(3, 'constellation_update', 'Constellation Update', 'Constellation');
INSERT INTO bizont_edms_general.permission_data (id, permission_name, permission_desc, permission_category) VALUES(4, 'constellation_view', 'Constellation View', 'Constellation');
INSERT INTO bizont_edms_general.permission_data (id, permission_name, permission_desc, permission_category) VALUES(5, 'hipma_create', 'Hipma Create', 'Hipma');
INSERT INTO bizont_edms_general.permission_data (id, permission_name, permission_desc, permission_category) VALUES(6, 'hipma_delete', 'Hipma Delete', 'Hipma');
INSERT INTO bizont_edms_general.permission_data (id, permission_name, permission_desc, permission_category) VALUES(7, 'hipma_update', 'Hipma Update', 'Hipma');
INSERT INTO bizont_edms_general.permission_data (id, permission_name, permission_desc, permission_category) VALUES(8, 'hipma_view', 'Hipma View', 'Hipma');
INSERT INTO bizont_edms_general.permission_data (id, permission_name, permission_desc, permission_category) VALUES(9, 'midwifery_create', 'Midwifery Create', 'Midwifery');
INSERT INTO bizont_edms_general.permission_data (id, permission_name, permission_desc, permission_category) VALUES(10, 'midwifery_delete', 'Midwifery Delete', 'Midwifery');
INSERT INTO bizont_edms_general.permission_data (id, permission_name, permission_desc, permission_category) VALUES(11, 'midwifery_update', 'Midwifery Update', 'Midwifery');
INSERT INTO bizont_edms_general.permission_data (id, permission_name, permission_desc, permission_category) VALUES(12, 'midwifery_view', 'Midwifery View', 'Midwifery');
