/* Replace with your SQL commands */

-- bizont_edms_general.role_permissions definition

CREATE TABLE bizont_edms_general.role_permissions (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	role_id int4 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT role_permissions_pk PRIMARY KEY (id),
	CONSTRAINT role_permissions_un UNIQUE (role_id, permission_id)
);
CREATE INDEX role_permissions_permission_id_idx ON bizont_edms_general.role_permissions USING btree (permission_id);
CREATE INDEX role_permissions_role_id_idx ON bizont_edms_general.role_permissions USING btree (role_id);

-- Permissions

ALTER TABLE bizont_edms_general.role_permissions OWNER TO postgres;
GRANT ALL ON TABLE bizont_edms_general.role_permissions TO postgres;