Constellation Health table
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH VALUES (6, 1, 'Ringo', 'Lennon', 'Yes, this is my legal name', 'Ringo Lennon', 'Dixisset', TO_DATE('1925-04-02', 'yyyy-mm-dd'), 'Yes, my health care card is from the Yukon.', '', '', '898-989-898', '11111', 'I want to be contacted by email', '', 'random@random.com', NULL, 3, 'Loremipsumhjbhjjh', 'Yes, I will need interpretation support', 'No, I don’t currently have a family physician', '', 'Dixisset', utl_raw.cast_to_raw('{ data:[5,7,15] }'), 1, 'Yes, I have other family members to include', TO_DATE('2023-02-03 01:05:03', 'yyyy-mm-dd hh24:mi:ss'), TO_DATE('2023-02-02 21:51:34', 'yyyy-mm-dd hh24:mi:ss'));
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH VALUES (7, 1, 'George', 'Starr', 'Yes, this is my legal name', 'George Starr', 'Oratione', TO_DATE('1930-09-07', 'yyyy-mm-dd'), 'No, my health care card is from a different province/territory.', 'Dixisset', 'Dixisset', '', '12345-6789', 'I want to be contacted by email', '', 'random@random.com', NULL, 1, '', NULL, 'Yes, I currently have a family physician', 'Oratione', '', utl_raw.cast_to_raw('{ data: [5,7,15] }'), 4, 'Yes, I have other family members to include', TO_DATE('2023-02-06 19:29:49', 'yyyy-mm-dd hh24:mi:ss'), TO_DATE('2023-02-02 21:51:34', 'yyyy-mm-dd hh24:mi:ss'));
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH VALUES (2, 3, 'Paul', 'Starr', 'Yes, this is my legal name', 'Paul Starr', 'Oratione', TO_DATE('1959-06-05', 'yyyy-mm-dd'), 'No, my health care card is from a different province/territory.', 'Dixisset', 'Dixisset', '', '12345-6789', 'I want to be contacted by email', '', 'random@random.com', '\N', 3, 'Oratione', 'No, I won’t need interpretation support', 'No, I don’t currently have a family physician', '', 'Loremipsum', utl_raw.cast_to_raw('{ data:[15] }'), 1, 'No, I don’t want to include anyone else on this application', TO_DATE('2023-02-01 22:43:55', 'yyyy-mm-dd hh24:mi:ss'), TO_DATE('2023-02-01 22:43:55', 'yyyy-mm-dd hh24:mi:ss'));
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH VALUES (1, 3, 'Paul', 'Lennon', 'No, this is not my legal name', 'Paul Lennon', 'Oratione', TO_DATE('1994-07-05', 'yyyy-mm-dd'), 'No, my health care card is from a different province/territory.', 'Dixisset', 'Loremipsum', '', '12345', 'I want to be contacted by email', '', 'test@test.com', '\N', 2, '', 'No, I won’t need interpretation support', 'Yes, I currently have a family physician', 'Loremipsum', '', utl_raw.cast_to_raw('{ data:[3,4,7] }'), 3, 'No, I don’t want to include anyone else on this application', TO_DATE('2023-02-01 18:55:55', 'yyyy-mm-dd hh24:mi:ss'), TO_DATE('2023-02-01 18:55:55', 'yyyy-mm-dd hh24:mi:ss'));
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH VALUES (5, 1, 'George', 'McCartney', 'No, this is not my legal name', 'What is your legal name?', 'Oratione', TO_DATE('1925-04-04', 'yyyy-mm-dd'), 'Yes, my health care card is from the Yukon.', '', '', '099-090-900', '11111', 'I want to be contacted by email', '', 'test@test.com', '\N', 2, '', 'Yes, I will need interpretation support', 'Yes, I currently have a family physician', 'Dixisset', '', utl_raw.cast_to_raw('{ data: [3,4,5] }'), 2, 'Yes, I have other family members to include', TO_DATE('2023-02-03 00:55:54', 'yyyy-mm-dd hh24:mi:ss'), TO_DATE('2023-02-03 00:55:54', 'yyyy-mm-dd hh24:mi:ss'));
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH VALUES (4, 3, 'George', 'Harrison', 'No, this is not my legal name', 'THIS IS MY LEGAL NAME', 'Oratione', TO_DATE('1996-07-08', 'yyyy-mm-dd'), 'Yes, my health care card is from the Yukon.', '', '', '934-909-090', '11111', 'I want to be contacted by phone', '(123) 456-7890', '', 'No, do not leave a message', 1, '', '\N', 'Yes, I currently have a family physician', 'Dixisset', '', utl_raw.cast_to_raw('{ data: [1,2,3,4,7] }'), 2, 'Yes, I have other family members to include', TO_DATE('2023-02-03 00:40:26', 'yyyy-mm-dd hh24:mi:ss'), TO_DATE('2023-02-03 00:40:26', 'yyyy-mm-dd hh24:mi:ss'));
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH VALUES (3, 3, 'George', 'McCartney', 'No, this is not my legal name', 'George McCartney', 'Dixisset', TO_DATE('1998-05-03', 'yyyy-mm-dd'), 'No, my health care card is from a different province/territory.', 'Loremipsum', 'Dixisset', '', '12345-6789', 'I want to be contacted by phone', '(098) 765-4321', '', 'No, do not leave a message', 2, '', 'Yes, I will need interpretation support', 'Yes, I currently have a family physician', 'Dixisset', '', utl_raw.cast_to_raw('{ data: [1,2,3,4,5,6,7,"TEST OTHER"] }'), 2, 'Yes, I have other family members to include', TO_DATE('2023-02-01 22:52:49', 'yyyy-mm-dd hh24:mi:ss'), TO_DATE('2023-02-01 22:52:49', 'yyyy-mm-dd hh24:mi:ss'));

Constellation health demographics
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DEMOGRAPHICS (id, value, DESCRIPTION) VALUES (1, 'yukonFN', 'Yukon First Nation');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DEMOGRAPHICS (id, value, DESCRIPTION) VALUES (2, 'non-yukonFN', 'Non-Yukon First Nation, Metis, or Inuit');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DEMOGRAPHICS (id, value, DESCRIPTION) VALUES (3, 'none', 'None of the above');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DEMOGRAPHICS (id, value, DESCRIPTION) VALUES (4, 'not-say', 'Prefer not to say');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DEMOGRAPHICS (id, value, DESCRIPTION) VALUES (5, 'they_yukonFN', 'Yukon First Nation');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DEMOGRAPHICS (id, value, DESCRIPTION) VALUES (6, 'they_non-yukonFN', 'Non-Yukon First Nation, Metis, or Inuit');

Constellation health diagnosis history
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (1, 'cancer', 'I have been diagnosed with cancer');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (2, 'palliative_diagnosis', 'I have a palliative care diagnosis');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (3, 'chronic_condition', 'I have been diagnosed with a chronic health condition (for example: COPD, diabetes, heart disease)');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (4, 'disability_limits_daily_act', 'I have a disability that limits my daily activities');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (5, 'mental_diagnosis', 'I have a mental health diagnosis or problem that impacts my daily activities');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (6, 'covid_complications', 'I have been diagnosed with long-term COVID-19 complications');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (7, 'alcohol_substance_misuse', 'I use or have a history of alcohol or substance misuse');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (8, 'they_cancer', 'They have been diagnosed with cancer');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (9, 'they_palliative_diagnosis', 'They have a palliative care diagnosis');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (10, 'they_chronic_condition', 'They have been diagnosed with a chronic health condition (for example: COPD, diabetes, heart disease)');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (11, 'they_disability_limits_daily_act', 'They have a disability that limits their daily activities');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (12, 'they_mental_diagnosis', 'They have a mental health diagnosis or problem that impacts their daily activities');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (13, 'they_covid_complications', 'They have been diagnosed with long-term COVID-19 complications');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (14, 'they_alcohol_substance_misuse', 'They use or have a history of alcohol or substance misuse');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY (id, value, DESCRIPTION) VALUES (15, 'none', 'None of the above');

Constellation health family members
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_FAMILY_MEMBERS VALUES (1, 6, 'Paul', 'Lennon', 'Yes, this is their legal name', '', 'Oratione', TO_DATE('2012-08-05', 'yyyy-mm-dd'), 'Yes, their health care card is from the Yukon.', '', '', '092-390-494', 'Loremipsum', 6, 'Oratione', 'Yes, they will need interpretation support', 'No, they don’t currently have a family physician', '', 'Oratione', utl_raw.cast_to_raw('{data: [15]}'), 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_FAMILY_MEMBERS VALUES (2, 7, 'George', 'McCartney', 'Yes, this is their legal name', '', 'Loremipsum', TO_DATE('1936-06-05', 'yyyy-mm-dd'), 'No, their health care card is from a different province/territory.', 'Oratione', 'Dixisset', '', 'Oratione', 4, '', '', 'No, they don’t currently have a family physician', '', 'Dixisset', utl_raw.cast_to_raw('{data: [8,12,15]}'), 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_FAMILY_MEMBERS VALUES (3, 7, 'jhbhjhbjhjbhhjbhjh', 'jhjhhjjhjbhbhj', 'No, this is not their legal name', 'jhbhjhbjhjbhhjbhjh jhjhhjjhjbhbhj', 'erer', TO_DATE('2017-05-04', 'yyyy-mm-dd'), 'No, their health care card is from a different province/territory.', 'erererer', 'erreer', '', 'rerere', 5, '', 'No, they won’t need interpretation support', 'Yes, they currently have a family physician', 'erreerer', '', utl_raw.cast_to_raw('{data: [8,13]}'), 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

Constellation health language
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_LANGUAGE (ID, VALUE, DESCRIPTION) VALUES (1, 'english', 'I prefer to receive services in English');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_LANGUAGE (ID, VALUE, DESCRIPTION) VALUES (2, 'french', 'I prefer to receive services in French');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_LANGUAGE (ID, VALUE, DESCRIPTION) VALUES (3, 'other_language', 'I prefer to receive services in another language');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_LANGUAGE (ID, VALUE, DESCRIPTION) VALUES (4, 'they_english', 'They prefer to receive services in English');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_LANGUAGE (ID, VALUE, DESCRIPTION) VALUES (5, 'they_french', 'They prefer to receive services in French');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_LANGUAGE (ID, VALUE, DESCRIPTION) VALUES (6, 'they_other_language', 'They prefer to receive services in another language');

Constellation health status
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_STATUS (ID, DESCRIPTION) VALUES (1, 'New/Unread');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_STATUS (ID, DESCRIPTION) VALUES (2, 'Entered');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_STATUS (ID, DESCRIPTION) VALUES (3, 'Declined');
INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_STATUS (ID, DESCRIPTION) VALUES (4, 'Closed');
