DROP TABLE bizont_edms_constellation_health.constellation_health;
CREATE TABLE bizont_edms_constellation_health.constellation_health (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    status NUMBER DEFAULT 1 NOT NULL,
    first_name NVARCHAR2(255),
    last_name NVARCHAR2(255),
    is_this_your_legal_name_ NVARCHAR2(255),
    your_legal_name NVARCHAR2(255),
    pronouns NVARCHAR2(100),
    date_of_birth date,
    have_yhcip NVARCHAR2(255),
    health_care_card NVARCHAR2(25),
    province NVARCHAR2(255),
    yhcip NVARCHAR2(25),
    postal_code NVARCHAR2(25),
    prefer_to_be_contacted NVARCHAR2(255),
    phone_number NVARCHAR2(255),
    email_address NVARCHAR2(255),
    leave_phone_message NVARCHAR2(255),
    language_prefer_to_receive_services NUMBER,
    preferred_language NVARCHAR2(100),
    interpretation_support NVARCHAR2(255),
    family_physician NVARCHAR2(255),
    current_family_physician NVARCHAR2(255),
    accessing_health_care NVARCHAR2(255),
    diagnosis BLOB,
    demographics_groups NUMBER,
    include_family_members NVARCHAR2(255),
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_constellation_health.constellation_health_demographics;
CREATE TABLE bizont_edms_constellation_health.constellation_health_demographics (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    value NVARCHAR2(100) NOT NULL,
    description NVARCHAR2(500) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_constellation_health.constellation_health_diagnosis_history;
CREATE TABLE bizont_edms_constellation_health.constellation_health_diagnosis_history (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    value NVARCHAR2(100) NOT NULL,
    description NVARCHAR2(500) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_constellation_health.constellation_health_family_members;
CREATE TABLE bizont_edms_constellation_health.constellation_health_family_members (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    constellation_health_id NUMBER,
    first_name_family_member NVARCHAR2(255),
    last_name_family_member NVARCHAR2(255),
    is_this_your_legal_name__family_member NVARCHAR2(255),
    your_legal_name_family_member NVARCHAR2(255),
    pronouns_family_member NVARCHAR2(100),
    date_of_birth_family_member date,
    have_yhcip_family_member NVARCHAR2(255),
    health_care_card_family_member NVARCHAR2(25),
    province_family_member NVARCHAR2(255),
    yhcip_family_member NVARCHAR2(25),
    relationship_family_member NVARCHAR2(255),
    language_prefer_to_receive_services_family_member NUMBER,
    preferred_language_family_member NVARCHAR2(100),
    interpretation_support_family_member NVARCHAR2(255),
    family_physician_family_member NVARCHAR2(255),
    current_family_physician_family_member NVARCHAR2(255),
    accessing_health_care_family_member NVARCHAR2(255),
    diagnosis_family_member BLOB,
    demographics_groups_family_member NUMBER,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_constellation_health.constellation_health_language;
CREATE TABLE bizont_edms_constellation_health.constellation_health_language (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    value NVARCHAR2(100) NOT NULL,
    description NVARCHAR2(500) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_constellation_health.constellation_status;
CREATE TABLE bizont_edms_constellation_health.constellation_status (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    description NVARCHAR2(500) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DECLARE 
exist_record NUMBER;
oldest_request NUMBER;
BEGIN
	SELECT COUNT(*) 
	INTO exist_record  
	FROM CONSTELLATION_HEALTH.CONSTELLATION_HEALTH
	WHERE  STATUS  <> 4  AND YOUR_LEGAL_NAME  = :NEW.YOUR_LEGAL_NAME AND DATE_OF_BIRTH  = :NEW.DATE_OF_BIRTH ;
	IF exist_record > 0 THEN
		SELECT ID
		INTO oldest_request
		FROM CONSTELLATION_HEALTH.CONSTELLATION_HEALTH
		WHERE STATUS <> 4  AND YOUR_LEGAL_NAME = :NEW.YOUR_LEGAL_NAME  AND DATE_OF_BIRTH  = :NEW.DATE_OF_BIRTH AND  ROWNUM <= 1
		ORDER BY CREATED_AT ;
	
		INSERT INTO CONSTELLATION_HEALTH.CONSTELLATION_DUPLICATED_REQUESTS  (ORIGINAL_ID , DUPLICATED_ID) VALUES (oldest_request, :NEW.ID);
   		
   END IF;

END;