DROP TABLE bizont_edms_midwifery.midwifery_services;
CREATE TABLE bizont_edms_midwifery.midwifery_services (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    confirmation_number NVARCHAR2(10),
    status NUMBER DEFAULT 1 NOT NULL,
    first_name NVARCHAR2(255),
    last_name NVARCHAR2(255),
    preferred_name NVARCHAR2(255),
    pronouns NVARCHAR2(255),
    date_of_birth DATE,
    yukon_health_insurance NUMBER,
    community_located NUMBER,
    preferred_language NUMBER,
    need_interpretation NUMBER,
    preferred_phone NVARCHAR2(255),
    preferred_email NVARCHAR2(255),
    okay_to_leave_message NUMBER,
    prefer_to_be_contacted NUMBER,
    when_was_the_first_day_of_your_last_period_ DATE,
    due_date DATE,
    date_confirmed NUMBER,
    first_pregnancy NUMBER,
    how_many_vaginal_births NVARCHAR2(255),
    how_many_c_section_births NVARCHAR2(255),
    complications_with_previous NUMBER,
    provide_details NVARCHAR2(4000),
    midwife_before NUMBER,
    where_to_give_birth NUMBER,
    medical_concerns NUMBER,
    provide_details2 NVARCHAR2(4000),
    have_you_had_primary_health_care NUMBER,
    menstrual_cycle_length NVARCHAR2(255),
    family_physician NUMBER,
    physician_s_name NVARCHAR2(255),
    major_medical_conditions NUMBER,
    provide_details3 NVARCHAR2(4000),
    do_you_identify_with_one_or_more_of_these_groups_and_communitie BLOB,
    how_did_you_find_out_about_the_midwifery_clinic_select_all_that BLOB,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_midwifery.midwifery_birth_locations;
CREATE TABLE bizont_edms_midwifery.midwifery_birth_locations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    name NVARCHAR2(255) NOT NULL,
    description NVARCHAR2(500) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_midwifery.midwifery_clinic_contact_types;
CREATE TABLE bizont_edms_midwifery.midwifery_clinic_contact_types (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    name NVARCHAR2(255) NOT NULL,
    description NVARCHAR2(500) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_midwifery.midwifery_community_locations;
CREATE TABLE bizont_edms_midwifery.midwifery_community_locations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    description NVARCHAR2(500) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_midwifery.midwifery_groups_communities;
CREATE TABLE bizont_edms_midwifery.midwifery_groups_communities (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    name NVARCHAR2(255) NOT NULL,
    description NVARCHAR2(500) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_midwifery.midwifery_languages;
CREATE TABLE bizont_edms_midwifery.midwifery_languages (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    description NVARCHAR2(500) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_midwifery.midwifery_options;
CREATE TABLE bizont_edms_midwifery.midwifery_options (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    field_name NVARCHAR2(100) NOT NULL,
    field_value boolean NOT NULL,
    description NVARCHAR2(500) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_midwifery.midwifery_preferred_contact_types;
CREATE TABLE bizont_edms_midwifery.midwifery_preferred_contact_types (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    name NVARCHAR2(255) NOT NULL,
    description NVARCHAR2(500) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_midwifery.midwifery_status;
CREATE TABLE bizont_edms_midwifery.midwifery_status (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    description NVARCHAR2(500) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);