DROP TABLE bizont_edms_hipma.health_information;
CREATE TABLE bizont_edms_hipma.health_information (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    confirmation_number NVARCHAR2(10),
    status NUMBER,
    what_type_of_request_do_you_want_to_make_ NUMBER,
    are_you_requesting_access_to_your_own_personal_health_informati NUMBER,
    select_the_situation_that_applies_ NUMBER,
    first_name_behalf NVARCHAR2(255),
    last_name_behalf NVARCHAR2(255),
    company_or_organization_optional_behalf NVARCHAR2(255),
    address_behalf NVARCHAR2(255),
    city_or_town_behalf NVARCHAR2(255),
    postal_code_behalf NVARCHAR2(50),
    email_address_behalf NVARCHAR2(255),
    phone_number_behalf NVARCHAR2(100),
    first_name NVARCHAR2(100),
    last_name NVARCHAR2(100),
    date_of_birth DATE,
    address NVARCHAR2(255),
    city_or_town NVARCHAR2(100),
    postal_code NVARCHAR2(50),
    email_address NVARCHAR2(255),
    phone_number NVARCHAR2(25),
    get_a_copy_of_your_health_information_ NUMBER,
    get_a_copy_of_your_activity_request NUMBER,
    name_of_health_and_social_services_program_area_optional_ BLOB,
    indicate_the_hss_system_s_you_would_like_a_record_of_user_activ BLOB,
    provide_details_about_your_request_ CLOB,
    date_from_ DATE,
    date_to_ DATE,
    date_range_is_unknown_or_i_need_help_identifying_the_date_range CHAR CHECK (date_range_is_unknown_or_i_need_help_identifying_the_date_range IN (0,1)),
    i_affirm_the_information_above_to_be_true_and_accurate_ NVARCHAR2(50),
    issued_identification NVARCHAR2(255),
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_hipma.hipma_copy_activity_request;
CREATE TABLE bizont_edms_hipma.hipma_copy_activity_request (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    description NVARCHAR2(255) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_hipma.hipma_copy_health_information;
CREATE TABLE bizont_edms_hipma.hipma_copy_health_information (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    description NVARCHAR2(255) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_hipma.hipma_files;
CREATE TABLE bizont_edms_hipma.hipma_files (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    hipma_id NUMBER,
    description NVARCHAR2(255) NOT NULL,
    file_name NVARCHAR2(500) NOT NULL,
    file_type NVARCHAR2(500) NOT NULL,
    file_size NVARCHAR2(500) NOT NULL,
    file_data BLOB NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_hipma.hipma_health_social_services_program;
CREATE TABLE bizont_edms_hipma.hipma_health_social_services_program (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    description NVARCHAR2(255) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_hipma.hipma_hss_systems;
CREATE TABLE bizont_edms_hipma.hipma_hss_systems (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    description NVARCHAR2(255) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_hipma.hipma_request_access_personal_health_information;
CREATE TABLE bizont_edms_hipma.hipma_request_access_personal_health_information (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    description NVARCHAR2(255) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_hipma.hipma_request_type;
CREATE TABLE bizont_edms_hipma.hipma_request_type (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    description NVARCHAR2(255) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_hipma.hipma_situations;
CREATE TABLE bizont_edms_hipma.hipma_situations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    description NVARCHAR2(255) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE bizont_edms_hipma.hipma_status;
CREATE TABLE bizont_edms_hipma.hipma_status (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    description NVARCHAR2(500) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP,
    updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

DECLARE 
exist_record NUMBER;
oldest_request NUMBER;

BEGIN
	SELECT COUNT(*) 
	INTO exist_record  
	FROM HIPMA.HEALTH_INFORMATION
	WHERE  status = 1 AND FIRST_NAME = :NEW.FIRST_NAME  AND LAST_NAME  = :NEW.LAST_NAME AND DATE_OF_BIRTH  = :NEW.DATE_OF_BIRTH;
	IF exist_record > 0 THEN
		SELECT health_information.id 
		INTO oldest_request
		FROM HIPMA.health_information 
		WHERE STATUS = 1 AND FIRST_NAME = :NEW.FIRST_NAME AND LAST_NAME  = :NEW.LAST_NAME AND DATE_OF_BIRTH  = :NEW.DATE_OF_BIRTH AND  ROWNUM <= 1
		ORDER BY CREATED_AT ;
	
		INSERT INTO HIPMA.HIPMA_DUPLICATED_REQUESTS (ORIGINAL_ID , DUPLICATED_ID) VALUES (oldest_request, :NEW.ID);
   		
   END IF;

END;