version: "3.7"
services:
    node_hss_backend:
        build: 
            context: "./"
            dockerfile: Dockerfile
        # command: ["nodemon", "server.js"]
        volumes:
            - "./:/usr/src/app"
            - "./.env.development:/.env"
        ports:
            - 3000:3000
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes: 
            - ./bkp:/host/bkp:rw
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local

