/* Replace with your SQL commands */

DROP TABLE IF EXISTS bizont_edms_constellation_health.constellation_health;
DROP TABLE IF EXISTS bizont_edms_constellation_health.constellation_health_language;
DROP TABLE IF EXISTS bizont_edms_constellation_health.constellation_health_diagnosis_history;
DROP TABLE IF EXISTS bizont_edms_constellation_health.constellation_health_demographics;
DROP TABLE IF EXISTS bizont_edms_constellation_health.constellation_health_family_members;